name: lint
on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: false
          submodules: recursive
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
        with:
          environments: lint
      - name: lint (if this step fails, please 'pixi run lint' locally and push the changes)
        run: pixi run lint
